version: '3.4'

services: 
  frontend-react:
    build:
      context: '../frontend-react'
    ports: 
      - '3000:3000'
    volumes: 
      - '../frontend-react:/home/node/app:delegated'
    command: 'run start'
    container_name: 'frontend-react'


  backend-node:
    build:
      context: '../backend-node'
    ports: 
      - '5000:3000'
      - '9000:9000'
    environment: 
      MONGODB_URI: mongodb://root:root@mongo/if18?authSource=admin
    volumes: 
      - '../backend-node:/home/node/app:delegated'
    command: 'run dev'
    container_name: 'backend-node'